version: '2.1'

volumes:
  static: {}

services:

    nginx:
        build: ./webserver/
        image: djanground/nginx
        volumes:
            - static:/app/static
        ports:
            - 80:80
        depends_on:
            - backend
        links:
            - backend

    redis:
        image: redis:4.0.2-alpine

    executor:
        build: ./executor/
        image: djanground/executor
        command: /bin/true

    backend:
        build: ./backend/
        image: djanground/backend
        volumes:
            - ./backend:/app
            - static:/app/static
        depends_on:
            - redis
        links:
            - redis
        ports:
            - 5000

    rq_worker:
        image: djanground/backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./backend:/app
        depends_on:
            - redis
            - backend
        links:
            - redis
        command: rq worker --url redis://redis:6379

    daphne:
        image: djanground/backend
        volumes:
            - ./backend:/app
        depends_on:
            - backend
        ports:
            - 5001
        command: daphne -b 0.0.0.0 -p 5001 djanground.asgi:channel_layer

    channels_worker:
        image: djanground/backend
        volumes:
            - ./backend:/app
        depends_on:
            - redis
            - backend
        links:
            - redis
        command: python manage.py runworker
