version: '2.1'

services:

    redis:
        image: redis:4.0.2-alpine

    executor:
        build: ./executor/
        image: djanground/executor

    worker:
        image: djanground/backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - redis
        links:
            - redis
        command: rq worker --url redis://redis:6379

    backend:
        build: ./backend/
        image: djanground/backend
        depends_on:
            - redis
        links:
            - redis
        command: python main.py
