version: '2.1'

volumes:
    static: {}
    certs: {}
    certs-data: {}


services:

    db:
        image: postgres:alpine

    nginx:
        build: ./webserver/
        image: dryorm/nginx
        volumes:
            - static:/app/static
            - certs:/etc/letsencrypt
            - certs-data:/data/letsencrypt
        ports:
            - 80:80
            - 443:443
        depends_on:
            - backend
        links:
            - backend

    redis:
        image: redis:4.0.2-alpine

    backend:
        build: ./backend/
        image: dryorm/backend
        volumes:
            - ./backend:/app
            - static:/app/static
        depends_on:
            - redis
            - db
        links:
            - redis
        ports:
            - 5000

    rq_worker:
        image: dryorm/backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./backend:/app
        depends_on:
            - redis
            - backend
        links:
            - redis
        command: rq worker --url redis://redis:6379

    daphne:
        image: dryorm/backend
        volumes:
            - ./backend:/app
        depends_on:
            - backend
        ports:
            - 5001
        command: daphne -b 0.0.0.0 -p 5001 dryorm.asgi:channel_layer

    channels_worker:
        image: dryorm/backend
        volumes:
            - ./backend:/app
        depends_on:
            - redis
            - backend
        links:
            - redis
        command: python manage.py runworker

    # Executors

    executor-python-django:
        build: ./executors/python-django
        image: dryorm-executor/python-django
        command: /bin/true
